# Generated by Django 3.2.15 on 2022-09-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('artist', models.TextField(max_length=200)),
                ('album', models.TextField(max_length=200)),
                ('lyrics', models.TextField()),
            ],
            options={
                'ordering': ['artist'],
            },
        ),
    ]
