# Generated by Django 3.2.15 on 2022-10-13 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('artist', models.TextField(max_length=200)),
                ('album', models.TextField(max_length=200)),
                ('lyrics', models.TextField()),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['artist'],
            },
        ),
    ]
